services:
  - type: web
    name: mockerview
    env: docker
    plan: free
    buildCommand: ./gradlew build -x test
    startCommand: java -jar build/libs/mockerview-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_OPTS
        value: -Xmx512m
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
