server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:mydiet
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  
  h2:
    console:
      enabled: true

claude:
  api-key: ${ANTHROPIC_API_KEY}
  base-url: https://api.anthropic.com/v1
  model: claude-3-haiku-20240307

logging:
  level:
    com.mydiet: INFO
    root: WARN